<table align="left" width=100%>
    <tr>
        <td width="20%">
            <img src="faculty.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                  <b> Assignment Questions </b>
                </font>
            </div>
        </td>
    </tr>
</table>

Total Marks:  30 Marks


### About the data set (COMPANY_Reviews)

The dataset contains Text reviews. The aim of this assignment is to classsify the review texts into two categories. 

Attribute information: 
 
Dataset has two columns:
Column2: Review Text
Column1: Two Classes. Positive and negative.

## Table of Content

1. **[Import Libraries](#lib)**
2. **[Load the Data  (5 Marks)](#prep)**
    - 2.1 - **[Read the Data   (1 Mark)](#read)**
    - 2.2 - **[Dispay the first ten rows (1 Mark) ](#dtype)**
    - 2.3 - **[Display the information about the data (1 Mark)](#drop)**
    - 2.4 - **[Encode the sentiment column values as 1 or 0 (2 Marks)](#dummy)**
3.  **[Data preprocessing  (7 Marks)](#prep)**
    - 3.1 - **[Remove special characters and html tags (2 Marks)](#read)**
    - 3.2 - **[Convert reviews into lowercase (1 Mark)](#dtype)**
    - 3.3 - **[Removal of stop words (2 Marks)](#drop)**
    - 3.4 - **[Apply stemming (2 Marks)](#dummy)**
4.**[Convert review text into feature vector and classification (18 Marks)](#prep)**
    - 4.1 - **[create BOW model (2 Marks)](#cut_off)**
    - 4.2 - **[Training data and Test data -split  (1 Mark)](#dtype)**
    - 4.3 - **[Define the Classification model (any one like NB, SVM or Random forest) train the model  (3 Marks) ](#drop)**
    - 4.4 - **[Classification metrics analysis (2 Marks)](#dummy)**
    - 4.5 - **[predict the class for your own review (2 Marks)](#dummy)**

    - 4.6 - **[create feature vector using tf-idf  (2 Marks)](#cut_off)**
    - 4.7 - **[Define the Classification model (any one like NB, SVM or Random forest) train the model (2 Marks)](#drop)**
    - 4.8 - **[Classification metrics analysis (2 Marks)](#dummy)**
    - 4.9 - **[predict the class for your own review (2 Marks) ](#dummy)**

        

<a id="lib"></a>
# 1. Import Libraries

**Let us import the required libraries.**

In [75]:
import numpy as np
import re
import pandas as pd
from string import punctuation
from nltk.corpus import stopwords
from nltk import word_tokenize
from sklearn.preprocessing import LabelEncoder
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score




2. Load the Data

2.1 Read the data

In [76]:
df= pd.read_csv("sentiment_analysis.csv",encoding=" ISO-8859-1")

2.2 Dispay the first ten rows

In [77]:
df.head(10)

Sentiment                                             Review
0  negative  The international electronic industry company ...
1  positive  With the new production plant the company woul...
2  positive  According to the company 's updated strategy f...
3  positive  FINANCING OF ASPOCOMP 'S GROWTH Aspocomp is ag...
4  positive  For the last quarter of 2010 , Componenta 's n...
5  positive  In the third quarter of 2010 , net sales incre...
6  positive  Operating profit rose to EUR 13.1 mn from EUR ...
7  positive  Operating profit totalled EUR 21.1 mn , up fro...
8  positive  TeliaSonera TLSN said the offer is in line wit...
9  positive  STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMEN...

2.3 Display the information about the data

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1967 entries, 0 to 1966
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Sentiment  1967 non-null   object
 1   Review     1967 non-null   object
dtypes: object(2)
memory usage: 30.9+ KB


2.4   Encode the sentiment column values as 1 or 0

In [79]:
lbl= LabelEncoder()
df['Sentiment_enc']=lbl.fit_transform(df['Sentiment'])
df

Sentiment                                             Review  \
0     negative  The international electronic industry company ...   
1     positive  With the new production plant the company woul...   
2     positive  According to the company 's updated strategy f...   
3     positive  FINANCING OF ASPOCOMP 'S GROWTH Aspocomp is ag...   
4     positive  For the last quarter of 2010 , Componenta 's n...   
...        ...                                                ...   
1962  negative  HELSINKI Thomson Financial - Shares in Cargote...   
1963  negative  LONDON MarketWatch -- Share prices ended lower...   
1964  negative  Operating profit fell to EUR 35.4 mn from EUR ...   
1965  negative  Net sales of the Paper segment decreased to EU...   
1966  negative  Sales in Finland decreased by 10.5 % in Januar...   

      Sentiment_enc  
0                 0  
1                 1  
2                 1  
3                 1  
4                 1  
...             ...  
1962              0  
1963              0  
1964              0  
1965              0  
1966              0  

[1967 rows x 3 columns]

3.  Data preprocessing

3.1 Remove special characters and html tags

In [99]:
def clean_text(text):
    text = re.sub('<.*?>', '', text)  # Remove HTML tags
    text = re.sub(r'[^a-zA-Z\s]', '', text)  # Remove special characters
    return text

df['Review'] = df['Review'].apply(clean_text)


3.2 - Convert reviews into lowercase

In [100]:
df['Review'] = df['Review'].str.lower()
        

3.3 - Removal of stop words

In [101]:
import nltk
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
df['Review'] = df['Review'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ROYAL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


3.4 - Apply stemming

In [102]:

stemmer = PorterStemmer()
df['Review'] = df['Review'].apply(lambda x: ' '.join([stemmer.stem(word) for word in x.split()]))

4.  Convert review text into feature vector and classification

4.1 - create BOW model 

In [103]:
cv = CountVectorizer()
X = cv.fit_transform(df['Review']).toarray()

In [104]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [105]:
y = df.iloc[:, -1].values

In [106]:
y

array([0, 1, 1, ..., 0, 0, 0])

4.2 - Training data and Test data -split

In [107]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 10)


4.3 - Define the Classification model (any one like NB, SVM or Random forest) train the model

In [108]:
classifier = GaussianNB()
classifier.fit(X_train, y_train)


y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 ...
 [0 1]
 [0 1]
 [0 1]]


4.4  Classification metrics analysis and plot the confusion matrix

In [109]:
cm = confusion_matrix(y_test, y_pred)
print(cm)


[[131  50]
 [133 277]]


In [110]:
accuracy_score(y_test, y_pred)

0.6903553299492385

4.5 - predict the class for your own review

In [111]:
new_review = 'The company laidoff the employee'
new_review = re.sub('[^a-zA-Z]', ' ', new_review)
new_review = new_review.lower()
new_review = new_review.split()
ps = PorterStemmer()
all_stopwords = stopwords.words('english')
all_stopwords.remove('not')
new_review = [ps.stem(word) for word in new_review if not word in set(all_stopwords)]
new_review = ' '.join(new_review)
new_corpus = [new_review]
new_X_test = cv.transform(new_corpus).toarray()
new_y_pred = classifier.predict(new_X_test)
print(new_y_pred)


[0]


4.6 - create feature vector using tf-idf

In [112]:
from sklearn.feature_extraction.text import TfidfVectorizer

tv = TfidfVectorizer(min_df=0., max_df=1., use_idf=True)
tv_matrix = tv.fit_transform(df['Review'])
tv_matrix = tv_matrix.toarray()

vocab = tv.get_feature_names()
pd.DataFrame(np.round(tv_matrix, 2), columns=vocab)

C:\Users\ROYAL\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


aaland  aalborg   ab  abb  abil  abl  abn  abp  abroad   ac  ...   yy  \
0        0.0      0.0  0.0  0.0   0.0  0.0  0.0  0.0     0.0  0.0  ...  0.0   
1        0.0      0.0  0.0  0.0   0.0  0.0  0.0  0.0     0.0  0.0  ...  0.0   
2        0.0      0.0  0.0  0.0   0.0  0.0  0.0  0.0     0.0  0.0  ...  0.0   
3        0.0      0.0  0.0  0.0   0.0  0.0  0.0  0.0     0.0  0.0  ...  0.0   
4        0.0      0.0  0.0  0.0   0.0  0.0  0.0  0.0     0.0  0.0  ...  0.0   
...      ...      ...  ...  ...   ...  ...  ...  ...     ...  ...  ...  ...   
1962     0.0      0.0  0.0  0.0   0.0  0.0  0.0  0.0     0.0  0.0  ...  0.0   
1963     0.0      0.0  0.0  0.0   0.0  0.0  0.0  0.0     0.0  0.0  ...  0.0   
1964     0.0      0.0  0.0  0.0   0.0  0.0  0.0  0.0     0.0  0.0  ...  0.0   
1965     0.0      0.0  0.0  0.0   0.0  0.0  0.0  0.0     0.0  0.0  ...  0.0   
1966     0.0      0.0  0.0  0.0   0.0  0.0  0.0  0.0     0.0  0.0  ...  0.0   

      zahariev  zaharova  zero  zgodi  zinc  zinclead  zoltan  zone  zoo  
0          0.0       0.0  0.00    0.0   0.0       0.0     0.0   0.0  0.0  
1          0.0       0.0  0.00    0.0   0.0       0.0     0.0   0.0  0.0  
2          0.0       0.0  0.00    0.0   0.0       0.0     0.0   0.0  0.0  
3          0.0       0.0  0.00    0.0   0.0       0.0     0.0   0.0  0.0  
4          0.0       0.0  0.33    0.0   0.0       0.0     0.0   0.0  0.0  
...        ...       ...   ...    ...   ...       ...     ...   ...  ...  
1962       0.0       0.0  0.00    0.0   0.0       0.0     0.0   0.0  0.0  
1963       0.0       0.0  0.00    0.0   0.0       0.0     0.0   0.0  0.0  
1964       0.0       0.0  0.00    0.0   0.0       0.0     0.0   0.0  0.0  
1965       0.0       0.0  0.00    0.0   0.0       0.0     0.0   0.0  0.0  
1966       0.0       0.0  0.00    0.0   0.0       0.0     0.0   0.0  0.0  

[1967 rows x 3888 columns]

4.7 Define the Classification model (any one like NB, SVM or Random forest) train the model

In [113]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [114]:
# Create a Random Forest model with n_estimators=30
random_forest = RandomForestClassifier(n_estimators=30)

# Fit the model on the training data
random_forest.fit(X_train, y_train)

# Make predictions on the test set
y_pred = random_forest.predict(X_test)

# Generate a classification report
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.79      0.64      0.71       181
           1       0.85      0.93      0.89       410

    accuracy                           0.84       591
   macro avg       0.82      0.78      0.80       591
weighted avg       0.84      0.84      0.83       591



4.8 - Classification metrics analysis

In [115]:
# Generate a classification report
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.79      0.64      0.71       181
           1       0.85      0.93      0.89       410

    accuracy                           0.84       591
   macro avg       0.82      0.78      0.80       591
weighted avg       0.84      0.84      0.83       591



4.9 - predict the class for your own review

In [116]:
new_review = 'The company laidoff the employee'
new_review = re.sub('[^a-zA-Z]', ' ', new_review)
new_review = new_review.lower()
new_review = new_review.split()
ps = PorterStemmer()
all_stopwords = stopwords.words('english')
all_stopwords.remove('not')
new_review = [ps.stem(word) for word in new_review if not word in set(all_stopwords)]
new_review = ' '.join(new_review)
new_corpus = [new_review]
new_X_test = cv.transform(new_corpus).toarray()
new_y_pred = classifier.predict(new_X_test)
print(new_y_pred)

[0]


In [117]:
new_review1 = 'The company increased the production'
new_review1 = re.sub('[^a-zA-Z]', ' ', new_review1)
new_review1 = new_review1.lower()
new_review1 = new_review1.split()
ps = PorterStemmer()
all_stopwords = stopwords.words('english')
all_stopwords.remove('not')
new_review1 = [ps.stem(word) for word in new_review1 if not word in set(all_stopwords)]
new_review1 = ' '.join(new_review1)
new_corpus1 = [new_review1]
new_X_test1 = cv.transform(new_corpus1).toarray()
new_y_pred1 = random_forest.predict(new_X_test1)
print(new_y_pred1)

[1]
